#Hugo configuration
title = "teasdf"
baseURL = "https:\/\/qweqw.asd.asd"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
